SELECTBOX_DEFAULT = " "
PITCH_COLOR = '#A2B38B'
STRIPE_COLOR = '#c2d59d'
LINE_COLOR = 'white'
COMPLETED_COLOR = '#B4FF9F'
INCOMPLETE_COLOR = '#990000'
INJURY_CLEARANCE_COLOR = '#FF8AAE'
OUT_COLOR = "purple"
PASS_OFFSIDE_COLOR = "#630606"
UNKNOWN_COLOR = "black"
SAVED_COLOR = "#FFC23C"
POST_COLOR = "#73A9AD"
SAVED_TO_POST_COLOR = "#371B58"
GOAL_ASSIST_COLOR = "#ffd700"
SHOT_ASSIST_COLOR = "#c0c0c0"
TEAMMATE_COLOR = "red"
OPPOSITION_COLOR = "blue"




